version: 2.1

jobs:
  build:
    docker:
      - image: php:8.2
        environment:
          APP_ENV: testing
          DB_CONNECTION: sqlite
          DB_DATABASE: ':memory:'
      - image: circleci/mysql:5.7
        environment:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: circle_test
          MYSQL_USER: homestead
          MYSQL_PASSWORD: secret
    steps:
      - checkout
      - run: |
          # Install unzip, 7z, libzip-dev, and git
          apt-get update
          apt-get install -y unzip
          apt-get install -y p7zip-full
          apt-get install -y libzip-dev
          apt-get install -y git

          # Install Composer globally
          curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
      - run: |
          # Enable zip extension for PHP
          docker-php-ext-configure zip
          docker-php-ext-install zip
      - run: composer install --no-interaction --prefer-dist --optimize-autoloader
      - run: cp .env.example .env
      - run: php artisan key:generate
      - run: php artisan migrate --force
      - run: vendor/bin/phpunit

workflows:
  version: 2
  build:
    jobs:
      - build
